# Generated by Django 3.2.9 on 2021-11-10 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_word', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
