# Generated by Django 3.2.9 on 2021-11-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='datetime',
            new_name='datetime_searched',
        ),
    ]
