# Generated by Django 3.2.9 on 2021-11-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsearch', '0002_rename_datetime_search_datetime_searched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='datetime_searched',
            field=models.DateTimeField(),
        ),
    ]
